
name: Nextflow test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: nf-core/setup-nextflow@v1
    - name: Test Nextflow pipeline
      run: |
        set -x
        echo "UID=$UID, GID=$GID"
        bash test/run-tests.sh gh
